### PR TITLE
fix(typescript): harden skill-aware audit trail for #2907

### PR DESCRIPTION
**Pull request by yuvrajsingh2428**
## Description

Ports the skill-aware audit trail hardening introduced in the Python implementation (#2572) for issue #1609 to the TypeScript SDK.

This change adds trusted skill metadata support, provenance trust markers, deterministic context hashing, and audit-chain coverage for skill metadata. It also adds tests covering metadata propagation, spoof resistance, deterministic hashing, and tampering detection.

## Type of Change

* [x] Bug fix (non-breaking change that fixes an issue)
* [x] Security fix

## Package(s) Affected

* [x] agent-governance

## Checklist

* [x] My code follows the project style guidelines (ruff check)
* [x] I have added tests that prove my fix/feature works
* [ ] All new and existing tests pass (pytest)
* [ ] I have updated documentation as needed
* [x] I have signed the Microsoft CLA

## Attribution & Prior Art

* [x] This contribution does not contain code copied or derived from other projects without attribution
* [x] Any external projects that inspired this design are credited in code comments or documentation
* [x] If this PR implements functionality similar to an existing open-source project, I have listed it below

**Prior art / related projects** (if any):

Python implementation introduced in #2572 for issue #1609.

## AI Assistance

* [x] I can explain every meaningful change in this PR: what it does, why, and what tradeoffs were considered
* [x] I have run tests and verification appropriate for this change
* [x] No part of this PR was autonomously submitted by an AI agent without my review
* [x] I have not used AI to generate review comments on others' PRs

If AI tools materially shaped this change, briefly note what was used:

ChatGPT and GitHub Copilot were used for implementation guidance and test generation. All generated output was reviewed and validated before inclusion.

## IP, Patents, and Licensing

* [x] This contribution does not implement patent-pending or patent-encumbered techniques
* [x] This contribution does not require an NDA or licensing agreement to understand or use
* [x] Any AI tools used have terms compatible with the MIT License

## Related Issues

Contributes to #2986.

Ports the TypeScript implementation to match the Python baseline introduced in #2572 for issue #1609.

### CODE REVIEW

**Comment by imran-siddique** [comment]
CLA is blocking this — microsoft-github-policy-service posted the agreement prompt in the PR. Please reply with `@microsoft-github-policy-service agree` so the CLA check passes, then we can give this a full review. The TypeScript port of the skill audit trail looks like the right direction.

**Comment by yuvrajsingh2428** [comment]
@microsoft-github-policy-service agree

**Review by imran-siddique — APPROVED** [review]
Solid implementation. `skillAuditMetadata` is correctly included in the SHA-256 chain-hash payload (the tamper-detection test proves it). `hashContext` uses stable key-sorted JSON before hashing so key insertion order doesn't affect the hash. Types are all optional so no breaking change. `provenanceSourceTrust: 'trusted'` clearly separates framework-verified metadata from unverified user data. LGTM.
